# CMake generated Testfile for 
# Source directory: /home/mbonjour/RELIC/relic/test
# Build directory: /home/mbonjour/RELIC/relic-target-bls48/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_bn "/home/mbonjour/RELIC/relic-target-bls48/bin/test_bn")
set_tests_properties(test_bn PROPERTIES  _BACKTRACE_TRIPLES "/home/mbonjour/RELIC/relic/test/CMakeLists.txt;10;add_test;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;18;ADD_MODULE;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;0;")
add_test(test_dv "/home/mbonjour/RELIC/relic-target-bls48/bin/test_dv")
set_tests_properties(test_dv PROPERTIES  _BACKTRACE_TRIPLES "/home/mbonjour/RELIC/relic/test/CMakeLists.txt;10;add_test;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;22;ADD_MODULE;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;0;")
add_test(test_fp "/home/mbonjour/RELIC/relic-target-bls48/bin/test_fp")
set_tests_properties(test_fp PROPERTIES  _BACKTRACE_TRIPLES "/home/mbonjour/RELIC/relic/test/CMakeLists.txt;10;add_test;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;26;ADD_MODULE;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;0;")
add_test(test_fpx "/home/mbonjour/RELIC/relic-target-bls48/bin/test_fpx")
set_tests_properties(test_fpx PROPERTIES  _BACKTRACE_TRIPLES "/home/mbonjour/RELIC/relic/test/CMakeLists.txt;10;add_test;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;30;ADD_MODULE;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;0;")
add_test(test_fb "/home/mbonjour/RELIC/relic-target-bls48/bin/test_fb")
set_tests_properties(test_fb PROPERTIES  _BACKTRACE_TRIPLES "/home/mbonjour/RELIC/relic/test/CMakeLists.txt;10;add_test;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;34;ADD_MODULE;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;0;")
add_test(test_fbx "/home/mbonjour/RELIC/relic-target-bls48/bin/test_fbx")
set_tests_properties(test_fbx PROPERTIES  _BACKTRACE_TRIPLES "/home/mbonjour/RELIC/relic/test/CMakeLists.txt;10;add_test;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;38;ADD_MODULE;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;0;")
add_test(test_ep "/home/mbonjour/RELIC/relic-target-bls48/bin/test_ep")
set_tests_properties(test_ep PROPERTIES  _BACKTRACE_TRIPLES "/home/mbonjour/RELIC/relic/test/CMakeLists.txt;10;add_test;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;42;ADD_MODULE;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;0;")
add_test(test_epx "/home/mbonjour/RELIC/relic-target-bls48/bin/test_epx")
set_tests_properties(test_epx PROPERTIES  _BACKTRACE_TRIPLES "/home/mbonjour/RELIC/relic/test/CMakeLists.txt;10;add_test;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;46;ADD_MODULE;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;0;")
add_test(test_eb "/home/mbonjour/RELIC/relic-target-bls48/bin/test_eb")
set_tests_properties(test_eb PROPERTIES  _BACKTRACE_TRIPLES "/home/mbonjour/RELIC/relic/test/CMakeLists.txt;10;add_test;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;50;ADD_MODULE;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;0;")
add_test(test_ed "/home/mbonjour/RELIC/relic-target-bls48/bin/test_ed")
set_tests_properties(test_ed PROPERTIES  _BACKTRACE_TRIPLES "/home/mbonjour/RELIC/relic/test/CMakeLists.txt;10;add_test;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;54;ADD_MODULE;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;0;")
add_test(test_ec "/home/mbonjour/RELIC/relic-target-bls48/bin/test_ec")
set_tests_properties(test_ec PROPERTIES  _BACKTRACE_TRIPLES "/home/mbonjour/RELIC/relic/test/CMakeLists.txt;10;add_test;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;58;ADD_MODULE;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;0;")
add_test(test_pc "/home/mbonjour/RELIC/relic-target-bls48/bin/test_pc")
set_tests_properties(test_pc PROPERTIES  _BACKTRACE_TRIPLES "/home/mbonjour/RELIC/relic/test/CMakeLists.txt;10;add_test;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;62;ADD_MODULE;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;0;")
add_test(test_pp "/home/mbonjour/RELIC/relic-target-bls48/bin/test_pp")
set_tests_properties(test_pp PROPERTIES  _BACKTRACE_TRIPLES "/home/mbonjour/RELIC/relic/test/CMakeLists.txt;10;add_test;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;66;ADD_MODULE;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;0;")
add_test(test_md "/home/mbonjour/RELIC/relic-target-bls48/bin/test_md")
set_tests_properties(test_md PROPERTIES  _BACKTRACE_TRIPLES "/home/mbonjour/RELIC/relic/test/CMakeLists.txt;10;add_test;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;70;ADD_MODULE;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;0;")
add_test(test_cp "/home/mbonjour/RELIC/relic-target-bls48/bin/test_cp")
set_tests_properties(test_cp PROPERTIES  _BACKTRACE_TRIPLES "/home/mbonjour/RELIC/relic/test/CMakeLists.txt;10;add_test;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;74;ADD_MODULE;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;0;")
add_test(test_rand "/home/mbonjour/RELIC/relic-target-bls48/bin/test_rand")
set_tests_properties(test_rand PROPERTIES  _BACKTRACE_TRIPLES "/home/mbonjour/RELIC/relic/test/CMakeLists.txt;10;add_test;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;77;ADD_MODULE;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;0;")
add_test(test_core "/home/mbonjour/RELIC/relic-target-bls48/bin/test_core")
set_tests_properties(test_core PROPERTIES  _BACKTRACE_TRIPLES "/home/mbonjour/RELIC/relic/test/CMakeLists.txt;10;add_test;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;78;ADD_MODULE;/home/mbonjour/RELIC/relic/test/CMakeLists.txt;0;")
